### ISSUE TITLE
Information regarding Inswapper model

### ISSUE THREAD

**Issue by thakral-kartik** [haofanwang/inswapper#17]
Hi, 
I really liked your work!!
Could you please give me more information about the model inswapper_128.onnx used, is it a GAN based or diffusion based face swapping model; or any resource that could help me clarify the question ?

Thanks in advance.

**Comment by jndietz** [comment]
You might need to ask this on the insightface github.  However, they're pretty secretive about the inner workings of the model to prevent others from training a new, higher resolution version.

**Comment by thakral-kartik** [comment]
Thanks!
